### ISSUE TITLE
Accuracy problem

### ISSUE THREAD

**Issue by fanninpm** [JianiC/rsv-genotype#1]
With LABEL v0.6.4 (released late September 2022), I get underwhelming accuracy when testing with most of [this supplementary data](https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Firv.12936&file=irv12936-sup-0005-supplementary_accession.csv).

[Here are the outputs for each accession I was able to collect.](https://github.com/JianiC/rsv-genotype/files/10281841/paper_hRSV_all_final.txt)

<details>
<summary>Summary Table</summary>

**CLADE**|**TP**|**Num**|**%Acc**
:-----:|:-----:|:-----:|:-----:
A.1|6|6|100.0%
A.2.1|14|14|100.0%
A.2.2|41|41|100.0%
A.2.3|6|9|66.7%
A.2.4|82|82|100.0%
A.3|6|6|100.0%
A.4|0|15|0.0%
A.5.1|0|19|0.0%
A.5.10|0|17|0.0%
A.5.11|0|131|0.0%
A.5.2|0|13|0.0%
A.5.3|0|104|0.0%
A.5.4|0|39|0.0%
A.5.5|0|11|0.0%
A.5.6|0|7|0.0%
A.5.7|0|26|0.0%
A.5.8|0|59|0.0%
A.5.9|0|81|0.0%
B.1|6|8|75.0%
B.2|33|35|94.3%
B.3|14|14|100.0%
B.4|4|4|100.0%
B.5|0|74|0.0%
B.5.1|0|7|0.0%
B.5.10|134|139|96.4%
B.5.2|3|4|75.0%
B.5.3|46|53|86.8%
B.5.4|9|9|100.0%
B.5.5|34|38|89.5%
B.5.6|15|15|100.0%
B.5.7|9|14|64.3%
B.5.8|112|114|98.2%
B.5.9|16|17|94.1%
**TOTAL**|**590**|**1225**|**48.2%**

</details>

**Comment by JianiC** [comment]
Hi, I have seen your issue. 
While this RSV module was built with an old LABEL version. But should not be a problem with new version. Based on previous tests, this module should be able to get the genotype correct, while having some errors with subclade (pseudo-genotype). I am guessing A.4 and A.5 module was not called probably under new version of LABEL?.  I will test it and get back to you. I assume you test with complete sequence that are directly extracted from GenBank.

**Comment by JianiC** [comment]
> With LABEL v0.6.4 (released late September 2022), I get underwhelming accuracy when testing with most of [this supplementary data](https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Firv.12936&file=irv12936-sup-0005-supplementary_accession.csv).
> 
> [Here are the outputs for each accession I was able to collect.](https://github.com/JianiC/rsv-genotype/files/10281841/paper_hRSV_all_final.txt)
> 
> Summary Table

3.	After reading this manuscript, I still feel there is a knowledge gap in the RSV evolution and epidemiology in South Korea. For example, the source of these RSV strains, and whether RSV in South Korea is introduced from other areas every year are more locally persistent. Whether the RSV evolution and epidemiology in South Korea report in this analysis is different from other local studies?

**Comment by JianiC** [comment]
> With LABEL v0.6.4 (released late September 2022), I get underwhelming accuracy when testing with most of [this supplementary data](https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Firv.12936&file=irv12936-sup-0005-supplementary_accession.csv).
> 
> [Here are the outputs for each accession I was able to collect.](https://github.com/JianiC/rsv-genotype/files/10281841/paper_hRSV_all_final.txt)
> 
> Summary Table

I have seen your issue. Thanks for letting me know.
While I build this module with an old LABEL version but do not think this should be a problem with the new version. . I assume you are testing with RSV sequences that are directly extracted from GenBank and test with module in this repo instead of rebuilding a LABEL module?

My self-validation reported high accuracy before and I actually test this module with partial RSV sequence (G/F only) recently and at least return the major genotype, while we have seen some potential errors with subclade. I am not surprised to see the problem with B.5.1, but it seems to me A.4 or A.5 genotype modules are not called properly after checking your test output, I will test with it again and get back to you soon

**Comment by fanninpm** [comment]
Here's a general outline of the steps I took (along with a few commands you might find useful):

- To prepare LABEL, I followed the instructions [here](https://github.com/JianiC/rsv-genotype/tree/master/LABEL), making sure to download LABEL v0.6.4 (released September 2022).
- To get the sequences:
  - I downloaded the [list of accessions and expected genotypes](https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Firv.12936&file=irv12936-sup-0005-supplementary_accession.csv), and opened it in a spreadsheet editor (I used LibreOffice Calc, but you can use whatever you have access to.)
  - I took the RSV-A accessions and RSV-B accessions and saved them to two separate TSV files. I did not include any that were labeled "NA", and I did not include headings.
  - I used AWK to split those two TSV files into several different TXT files, each named after its assigned genotype. I saved these text files into a `genotypes/` folder for convenience. [^awk]
  - From there, you could feed those into `efetch`, but I used `seqkit grep` to filter sequences from a file with an Entrez search I had done previously. I used `sed` to attach the genotype to the `>` line of each record. [^fetch-seqs]
- Using `cat`, I concatenated the resulting FASTA files into one big FASTA file.
- Then, I ran `time IFX_LOCAL_PROCS=24 ./LABEL paper_hRSV_all.fa paper_hRSV_all RSV`. [^run-label]

If you have any questions about this, please let me know.

[^awk]: `mkdir genotypes`, followed by `awk '{print $1 > "genotypes/" $2 ".txt"}' paper_genotypes_a.tsv`. AWK usually splits on tab characters.
[^fetch-seqs]: Something like `for i in $(find genotypes/ -name '*.txt' -exec basename {} .txt \; | sort); do efetch -db nucleotide -input "genotypes/${i}.txt" -format fasta | sed -e '/>/s/ .*$//' -e "/>/s/\$/ {$i}/" > genotypes/${i}.fa; done` would do the trick.
  The `find` command finds all files in `genotypes/` that end in `.txt` and executes `basename` on them to remove both the directory prefix and the `.txt` suffix.
  `efetch` uses the `-input` flag to read accessions from a file.
  The `sed` expressions say, "first, for all lines that have `>`, take the first space and all characters until the end of the line and replace them with nothing; second, for all lines that have '>', take the end of the line and replace it with a space, a left curly brace, the contents of `$i`, and a right curly brace".
[^run-label]: My VM has 24 cores, so I set `IFX_LOCAL_PROCS` equal to 24. I added `time` to the beginning of the command so that the shell can time its execution.

**Comment by JianiC** [comment]
> Here's a general outline of the steps I took (along with a few commands you might find useful):
> 
> * To prepare LABEL, I followed the instructions [here](https://github.com/JianiC/rsv-genotype/tree/master/LABEL), making sure to download LABEL v0.6.4 (released September 2022).
> * To get the sequences:
>   
>   * I downloaded the [list of accessions and expected genotypes](https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Firv.12936&file=irv12936-sup-0005-supplementary_accession.csv), and opened it in a spreadsheet editor (I used LibreOffice Calc, but you can use whatever you have access to.)
>   * I took the RSV-A accessions and RSV-B accessions and saved them to two separate TSV files. I did not include any that were labeled "NA", and I did not include headings.
>   * I used AWK to split those two TSV files into several different TXT files, each named after its assigned genotype. I saved these text files into a `genotypes/` folder for convenience. [1](#user-content-fn-awk-6bc901d622556503c92a28dbcbe38b0e)
>   * From there, you could feed those into `efetch`, but I used `seqkit grep` to filter sequences from a file with an Entrez search I had done previously. I used `sed` to attach the genotype to the `>` line of each record. [2](#user-content-fn-fetch-seqs-6bc901d622556503c92a28dbcbe38b0e)
> * Using `cat`, I concatenated the resulting FASTA files into one big FASTA file.
> * Then, I ran `time IFX_LOCAL_PROCS=24 ./LABEL paper_hRSV_all.fa paper_hRSV_all RSV`. [3](#user-content-fn-run-label-6bc901d622556503c92a28dbcbe38b0e)
> 
> If you have any questions about this, please let me know.
> 
> ## Footnotes
> 1. `mkdir genotypes`, followed by `awk '{print $1 > "genotypes/" $2 ".txt"}' paper_genotypes_a.tsv`. AWK usually splits on tab characters. [↩](#user-content-fnref-awk-6bc901d622556503c92a28dbcbe38b0e)
> 2. Something like `for i in $(find genotypes/ -name '*.txt' -exec basename {} .txt \; | sort); do efetch -db nucleotide -input "genotypes/${i}.txt" -format fasta | sed -e '/>/s/ .*$//' -e "/>/s/\$/ {$i}/" > genotypes/${i}.fa; done` would do the trick.
>    The `find` command finds all files in `genotypes/` that end in `.txt` and executes `basename` on them to remove both the directory prefix and the `.txt` suffix.
>    `efetch` uses the `-input` flag to read accessions from a file.
>    The `sed` expressions say, "first, for all lines that have `>`, take the first space and all characters until the end of the line and replace them with nothing; second, for all lines that have '>', take the end of the line and replace it with a space, a left curly brace, the contents of `$i`, and a right curly brace". [↩](#user-content-fnref-fetch-seqs-6bc901d622556503c92a28dbcbe38b0e)
> 3. My VM has 24 cores, so I set `IFX_LOCAL_PROCS` equal to 24. I added `time` to the beginning of the command so that the shell can time its execution. [↩](#user-content-fnref-run-label-6bc901d622556503c92a28dbcbe38b0e)

Thanks for sharing this. I have seen where the problem comes from. We do the genotyping module based on the coding region (CDS concatenate), while the Entrez search includes the non-coding part. When the sequences come from the same group, the length of non-coding regions cause accuracy problem in LABEL. Currently working on this issue now

**Comment by JianiC** [comment]
> Here's a general outline of the steps I took (along with a few commands you might find useful):
> 
> * To prepare LABEL, I followed the instructions [here](https://github.com/JianiC/rsv-genotype/tree/master/LABEL), making sure to download LABEL v0.6.4 (released September 2022).
> * To get the sequences:
>   
>   * I downloaded the [list of accessions and expected genotypes](https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Firv.12936&file=irv12936-sup-0005-supplementary_accession.csv), and opened it in a spreadsheet editor (I used LibreOffice Calc, but you can use whatever you have access to.)
>   * I took the RSV-A accessions and RSV-B accessions and saved them to two separate TSV files. I did not include any that were labeled "NA", and I did not include headings.
>   * I used AWK to split those two TSV files into several different TXT files, each named after its assigned genotype. I saved these text files into a `genotypes/` folder for convenience. [1](#user-content-fn-awk-3ac1c42b70c361a8dfaadf09eb4b1313)
>   * From there, you could feed those into `efetch`, but I used `seqkit grep` to filter sequences from a file with an Entrez search I had done previously. I used `sed` to attach the genotype to the `>` line of each record. [2](#user-content-fn-fetch-seqs-3ac1c42b70c361a8dfaadf09eb4b1313)
> * Using `cat`, I concatenated the resulting FASTA files into one big FASTA file.
> * Then, I ran `time IFX_LOCAL_PROCS=24 ./LABEL paper_hRSV_all.fa paper_hRSV_all RSV`. [3](#user-content-fn-run-label-3ac1c42b70c361a8dfaadf09eb4b1313)
> 
> If you have any questions about this, please let me know.
> 
> ## Footnotes
> 1. `mkdir genotypes`, followed by `awk '{print $1 > "genotypes/" $2 ".txt"}' paper_genotypes_a.tsv`. AWK usually splits on tab characters. [↩](#user-content-fnref-awk-3ac1c42b70c361a8dfaadf09eb4b1313)
> 2. Something like `for i in $(find genotypes/ -name '*.txt' -exec basename {} .txt \; | sort); do efetch -db nucleotide -input "genotypes/${i}.txt" -format fasta | sed -e '/>/s/ .*$//' -e "/>/s/\$/ {$i}/" > genotypes/${i}.fa; done` would do the trick.
>    The `find` command finds all files in `genotypes/` that end in `.txt` and executes `basename` on them to remove both the directory prefix and the `.txt` suffix.
>    `efetch` uses the `-input` flag to read accessions from a file.
>    The `sed` expressions say, "first, for all lines that have `>`, take the first space and all characters until the end of the line and replace them with nothing; second, for all lines that have '>', take the end of the line and replace it with a space, a left curly brace, the contents of `$i`, and a right curly brace". [↩](#user-content-fnref-fetch-seqs-3ac1c42b70c361a8dfaadf09eb4b1313)
> 3. My VM has 24 cores, so I set `IFX_LOCAL_PROCS` equal to 24. I added `time` to the beginning of the command so that the shell can time its execution. [↩](#user-content-fnref-run-label-3ac1c42b70c361a8dfaadf09eb4b1313)

We temporality provide an RSV complete module to fix this problem. [https://github.com/JianiC/rsv-genotype/tree/master/LABEL/RSV_complete](url)  I test it with sequences that are directly from Genbank/ GISAID. While some sequences might be misclassified at the subclade level, most sequences can be classified into the correct genotype. All c-B.5 sequences are classified into a subclade belong genotype c-B..5. 
--------------------------------------
     CLADE	   TP	  Num	  %Acc
--------------------------------------
       A.1	    6	    6	100.0%
     A.2.1	   16	   16	100.0%
     A.2.2	   41	   41	100.0%
     A.2.3	    9	    9	100.0%
     A.2.4	   85	   85	100.0%
       A.3	    6	    6	100.0%
       A.4	   15	   15	100.0%
     A.5.1	   20	   20	100.0%
    A.5.10	   15	   17	 88.2%
    A.5.11	  132	  132	100.0%
     A.5.2	   13	   13	100.0%
     A.5.3	  105	  105	100.0%
     A.5.4	   39	   39	100.0%
     A.5.5	   10	   11	 90.9%
     A.5.6	    4	    8	 50.0%
     A.5.7	   27	   27	100.0%
     A.5.8	   57	   61	 93.4%
     A.5.9	   82	   83	 98.8%
       B.1	    7	   10	 70.0%
       B.2	   37	   42	 88.1%
       B.3	   14	   16	 87.5%
       B.4	    4	    4	100.0%
     B.5.1	    1	    7	 14.3%
    B.5.10	  136	  141	 96.5%
     B.5.2	    2	    4	 50.0%
     B.5.3	   49	   53	 92.5%
     B.5.4	    9	    9	100.0%
     B.5.5	   36	   43	 83.7%
     B.5.6	   17	   17	100.0%
     B.5.7	   15	   15	100.0%
     B.5.8	  114	  118	 96.6%
     B.5.9	   16	   17	 94.1%
     c-B.5	    0	   77	  0.0%
--------------------------------------
     TOTAL	 1139	 1267	 89.9%
--------------------------------------
Let me know if you have further questions.
